#!/usr/bin/env bash
# Install and configure HAproxy on a server.
sudo apt -y update
sudo apt -y install haproxy
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend http
    bind *:80
    mode http
    default_backend web_backend

backend web_backend
    balance roundrobin
    server 472385-web-01 100.26.49.195:80 check
    server 472385-web-02 54.152.70.222:80 check
EOF

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
