#!/usr/bin/env bash
# configures Nginx to run, and listen on port 80 of all the server’s active IPv4 IPs
# remove default nginx file config
rm /etc/nginx/sites-enabled/default
# nginx config to listen on port 80 for ll IPV4 Ips
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
