#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# but for the 9th iteration, displays Best School and then Hi on a new line
school="Best School"
count=1
while [[ $count -lt 10 ]]
do
    if [[ $count -eq 9 ]]
    then
        echo "Hi"
    fi
    ((count++))
    echo "${school}"
done
