#!/usr/bin/env bash
# A script that configures an Ubuntu server with the below requirements.
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
# Backup the original host file
sudo cp /etc/hosts /etc/hosts.bak
sudo bash -c 'echo "127.0.0.2 localhost" > /etc/hosts'
sudo bash -c 'echo "8.8.8.8 facebook.com" >> /etc/hosts'
