#!/usr/bin/env bash
# fix container so that nginx is running as the nginx user not root
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
sudo pkill 'apache2'
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
